export const categorySeed = {
    KitchenCategories: {
        Appliances: [
            "Toasters",
            "Blenders",
            "Coffee Machines",
            "Juicers",
            "Popcorn Makers",
            "Tea Kettles",
            "Water Heaters",
            "Waffle Makers",
            "Other Appliances",
        ],
        Cookware: ["Pots", "Pans", "Forms", "Other Cookware"],
        Cutlery: [
            "Knives",
            "Forks",
            "Tea Spoons",
            "Soup Spoons",
            "Chop Sticks",
            "Other Cutlery",
        ],
        Dishes: [
            "Plates",
            "Mugs",
            "Bowls",
            "Cups",
            "Platters",
            "Trays",
            "Tea Pots",
            "Other Dishes",
        ],
        OtherKitchenCategories: "Other Kitchen Categories",
    },
};

export const detailsSeed = {
    Brands: [
        "Melitta",
        "WMF",
        "Krups",
        "Philips",
        "Severin",
        "AEG",
        "DeLonghi",
        "Siemens",
        "Miele",
        "Nespresso",
        "Tefal",
        "Tchibo",
        "Bialetti",
        "Bosch",
        "Kenwood",
        "Bodum",
        "Gaggia",
        "Bauknecht",
        "BEKO",
        "Zwilling",
        "Clatronic",
        "Gorenje",
        "Grundig",
        "Other",
        "Ikea",
        "Liebherr",
        "ok",
        "Privileg",
        "Russell Hobbs",
        "KPM",
    ],
    Conditions: ["*****", "****", "***", "**", "*"],
    Age: [
        "Less than a month",
        "Less than a year",
        "Less than five years",
        "More than five years",
    ],
    EnergyEfficiencyClass: [
        "A+++",
        "A++",
        "A+",
        "A",
        "B",
        "C",
        "D",
        "E",
        "F",
        "G",
    ],
};
