GET http://localhost:3000/api/editproduct?identifier=5c9e989f-d2a2-40eb-bae7-0a4f2e4d646c

###
PUT http://localhost:3000/api/editproduct?path=Kitchen,Appliances&updateitem=
Content-Type: application/json

{
  "title": "my edited item"
}
