
POST http://localhost:3000/api/item?path=Kitchen,Appliances&user=a984d4b7-17b9-4810-ac22-4656ac5a73e6
Content-Type: application/json

{
  "title": "Coffee Machine",
  "images": ["x"],
  "description": "damn good coffee",
  "sellType": "FREE",
  "class": "Coffee Machines",
  "details": {
    "Brand": "Melitta",
    "Age": "Less than a month",
    "Condition": "*****",
    "EnergyEfficiencyClass": "C"
  }
}

###
PUT http://localhost:3000/api/item?updateitem=9d449540-6dc7-47e9-9d07-37c8c87e5613&recipient=3c98648e-50f5-4143-96e5-12153e415808

###
PUT http://localhost:3000/api/item?updateitem=f8e171e8-f06c-4d0f-98a5-135afc4f7936
Content-Type: application/json

["test", "test", "test"]

###

GET http://localhost:3000/api/item?identifier=01c35fd-46e1-41b0-be49-ab6eea80ca47

###
DELETE http://localhost:3000/api/item?identifier=12562128-46b9-487a-8588-5fec70490052



