POST http://localhost:3000/api/item
Content-Type: application/json

    {
  "title": "Nespresso",
  "userId": "b7d7b045-e207-48e7-84d4-4aa48995452b",
  "images": {},
  "description": "damn good coffee",
  "sellType": "FREE",
  "details": {
    "Brand": "Melitta",
    "Age": "Less than a month",
    "Condition": "*****",
    "EnergyEfficiencyClass": "A+"
    },
  "subcategory": "Coffee Machines"
}