
POST http://localhost:3000/api/item?path=Kitchen,Appliances&user=01df4dcb-38b4-4437-a62a-f8e3c1003ff2
Content-Type: application/json

{
  "title": "Nespresso",
  "images": ["x"],
  "description": "damn good coffee",
  "sellType": "FREE",
  "class": "Coffee Machines",
  "details": {
    "Brand": "Melitta",
    "Age": "Less than a month",
    "Condition": "*****",
    "EnergyEfficiencyClass": "C"
  }
}

###
PUT http://localhost:3000/api/item?updateitem=9d449540-6dc7-47e9-9d07-37c8c87e5613&recipient=3c98648e-50f5-4143-96e5-12153e415808

###

GET http://localhost:3000/api/item?identifier=12562128-46b9-487a-8588-5fec70490052

###
DELETE http://localhost:3000/api/item?identifier=12562128-46b9-487a-8588-5fec70490052



