
POST http://localhost:3000/api/item?user=0e48788c-c88e-4a03-897c-f7f3f5edf59c&path=Kitchen,Appliances
Content-Type: application/json

{
  "title": "Nespresso",
  "images": ["x"],
  "description": "damn good coffee",
  "sellType": "FREE",
  "class": "Coffee Machines",
  "details": {
    "Brand": "Melitta",
    "Age": "Less than a month",
    "Condition": "*****",
    "EnergyEfficiencyClass": "C"
  }
}

###

GET http://localhost:3000/api/item?identifier=629e6538-ce13-4b8f-9101-f46f82ea8dbd

###
DELETE http://localhost:3000/api/item?identifier=965816e5-975d-4d5c-9250-af1acb65722b



